
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/kite-traders
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 100
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: ./run.sh
      timeout: 100
      runas: ec2-user
