
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/kite_traders
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 100
      runas: ec2-user
  BeforeInstall:
    - location: before_install.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: run.sh
      timeout: 100
      runas: ec2-user
